from typing import Optional

from sqlalchemy import Float, ForeignKey, Integer, Text, text
from sqlalchemy.orm import Mapped, mapped_column, relationship
from observation.database.models.base import Base


class FeatureWindow(Base):
    __tablename__ = "feature_windows"
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    run_id: Mapped[int] = mapped_column(ForeignKey("observation_runs.run_id", ondelete="CASCADE"))
    window_start_ts: Mapped[str] = mapped_column(Text)
    window_end_ts: Mapped[str] = mapped_column(Text)
    entity_type: Mapped[str] = mapped_column(Text)
    entity_id: Mapped[str] = mapped_column(Text)
    label: Mapped[Optional[int]] = mapped_column(Integer)
    scenario: Mapped[Optional[str]] = mapped_column(Text)
    attack_family: Mapped[Optional[str]] = mapped_column(Text)
    attack_technique: Mapped[Optional[str]] = mapped_column(Text)
    feature_version: Mapped[str] = mapped_column(Text)
    aggregation_version: Mapped[str] = mapped_column(Text)
    event_count: Mapped[int] = mapped_column(Integer, default=0)
    tcp_connect_count: Mapped[int] = mapped_column(Integer, default=0)
    tcp_close_count: Mapped[int] = mapped_column(Integer, default=0)
    dns_query_count: Mapped[int] = mapped_column(Integer, default=0)
    tls_connection_count: Mapped[int] = mapped_column(Integer, default=0)
    http_request_count: Mapped[int] = mapped_column(Integer, default=0)
    ssh_attempt_count: Mapped[int] = mapped_column(Integer, default=0)
    unique_dst_ip_count: Mapped[int] = mapped_column(Integer, default=0)
    unique_dst_port_count: Mapped[int] = mapped_column(Integer, default=0)
    unique_src_port_count: Mapped[int] = mapped_column(Integer, default=0)
    external_dst_ip_count: Mapped[int] = mapped_column(Integer, default=0)
    private_dst_ip_count: Mapped[int] = mapped_column(Integer, default=0)
    total_bytes_in: Mapped[int] = mapped_column(Integer, default=0)
    total_bytes_out: Mapped[int] = mapped_column(Integer, default=0)
    total_packets_in: Mapped[int] = mapped_column(Integer, default=0)
    total_packets_out: Mapped[int] = mapped_column(Integer, default=0)
    mean_flow_duration_sec: Mapped[Optional[float]] = mapped_column(Float)
    max_flow_duration_sec: Mapped[Optional[float]] = mapped_column(Float)
    failed_connection_count: Mapped[int] = mapped_column(Integer, default=0)
    failed_connection_ratio: Mapped[Optional[float]] = mapped_column(Float)
    connections_per_sec: Mapped[Optional[float]] = mapped_column(Float)
    bytes_per_sec_in: Mapped[Optional[float]] = mapped_column(Float)
    bytes_per_sec_out: Mapped[Optional[float]] = mapped_column(Float)
    packets_per_sec_in: Mapped[Optional[float]] = mapped_column(Float)
    packets_per_sec_out: Mapped[Optional[float]] = mapped_column(Float)
    interarrival_mean_ms: Mapped[Optional[float]] = mapped_column(Float)
    interarrival_std_ms: Mapped[Optional[float]] = mapped_column(Float)
    interarrival_p95_ms: Mapped[Optional[float]] = mapped_column(Float)
    dst_port_entropy: Mapped[Optional[float]] = mapped_column(Float)
    dst_ip_entropy: Mapped[Optional[float]] = mapped_column(Float)
    well_known_port_ratio: Mapped[Optional[float]] = mapped_column(Float)
    high_port_ratio: Mapped[Optional[float]] = mapped_column(Float)
    external_destination_ratio: Mapped[Optional[float]] = mapped_column(Float)
    unique_domain_count: Mapped[int] = mapped_column(Integer, default=0)
    nxdomain_count: Mapped[int] = mapped_column(Integer, default=0)
    nxdomain_ratio: Mapped[Optional[float]] = mapped_column(Float)
    mean_domain_length: Mapped[Optional[float]] = mapped_column(Float)
    max_domain_length: Mapped[Optional[int]] = mapped_column(Integer)
    subdomain_depth_mean: Mapped[Optional[float]] = mapped_column(Float)
    unique_resolved_ip_count: Mapped[int] = mapped_column(Integer, default=0)
    dns_response_latency_mean_ms: Mapped[Optional[float]] = mapped_column(Float)
    dns_response_latency_p95_ms: Mapped[Optional[float]] = mapped_column(Float)
    mean_label_length: Mapped[Optional[float]] = mapped_column(Float)
    max_label_length: Mapped[Optional[int]] = mapped_column(Integer)
    domain_label_entropy_mean: Mapped[Optional[float]] = mapped_column(Float)
    base32_like_ratio: Mapped[Optional[float]] = mapped_column(Float)
    base64_like_ratio: Mapped[Optional[float]] = mapped_column(Float)
    hex_like_ratio: Mapped[Optional[float]] = mapped_column(Float)
    unique_sni_count: Mapped[int] = mapped_column(Integer, default=0)
    missing_sni_count: Mapped[int] = mapped_column(Integer, default=0)
    missing_sni_ratio: Mapped[Optional[float]] = mapped_column(Float)
    unique_ja4_count: Mapped[int] = mapped_column(Integer, default=0)
    ja4_entropy: Mapped[Optional[float]] = mapped_column(Float)
    rare_ja4_ratio: Mapped[Optional[float]] = mapped_column(Float)
    tls_version_distribution: Mapped[Optional[str]] = mapped_column(Text)
    most_common_ja4: Mapped[Optional[str]] = mapped_column(Text)
    most_common_ja4_count: Mapped[Optional[int]] = mapped_column(Integer)
    http_unique_host_count: Mapped[int] = mapped_column(Integer, default=0)
    http_methods_distribution: Mapped[Optional[str]] = mapped_column(Text)
    http_status_2xx_ratio: Mapped[Optional[float]] = mapped_column(Float)
    http_status_4xx_ratio: Mapped[Optional[float]] = mapped_column(Float)
    http_status_5xx_ratio: Mapped[Optional[float]] = mapped_column(Float)
    mean_path_length: Mapped[Optional[float]] = mapped_column(Float)
    mean_content_length: Mapped[Optional[float]] = mapped_column(Float)
    process_exec_count: Mapped[int] = mapped_column(Integer, default=0)
    unique_binary_count: Mapped[int] = mapped_column(Integer, default=0)
    shell_spawn_count: Mapped[int] = mapped_column(Integer, default=0)
    interpreter_spawn_count: Mapped[int] = mapped_column(Integer, default=0)
    process_tree_depth_max: Mapped[Optional[int]] = mapped_column(Integer)
    sensitive_file_event_count: Mapped[int] = mapped_column(Integer, default=0)
    privilege_event_count: Mapped[int] = mapped_column(Integer, default=0)
    sudo_exec_count: Mapped[int] = mapped_column(Integer, default=0)
    pkexec_count: Mapped[int] = mapped_column(Integer, default=0)
    su_exec_count: Mapped[int] = mapped_column(Integer, default=0)
    capability_event_count: Mapped[int] = mapped_column(Integer, default=0)
    seconds_since_last_privilege_event: Mapped[Optional[float]] = mapped_column(Float)
    seconds_since_last_sensitive_file_access: Mapped[Optional[float]] = mapped_column(Float)
    network_events_after_privilege_event: Mapped[Optional[int]] = mapped_column(Integer)
    network_events_after_sensitive_file_access: Mapped[Optional[int]] = mapped_column(Integer)
    ssh_success_count: Mapped[int] = mapped_column(Integer, default=0)
    ssh_failure_count: Mapped[int] = mapped_column(Integer, default=0)
    ssh_failure_ratio: Mapped[Optional[float]] = mapped_column(Float)
    ssh_session_count: Mapped[int] = mapped_column(Integer, default=0)
    mean_ssh_session_duration_sec: Mapped[Optional[float]] = mapped_column(Float)
    contributing_event_ids: Mapped[Optional[str]] = mapped_column(Text)
    total_flow_count: Mapped[int] = mapped_column(Integer, default=0)
    created_at: Mapped[str] = mapped_column(Text, server_default=text("(datetime('now'))"))
    run: Mapped["ObservationRun"] = relationship(back_populates="feature_windows")
