"""baseline schema

Revision ID: 16c12e3dc85c
Revises: 
Create Date: 2026-09-14 13:39:43.639172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16c12e3dc85c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observation_runs',
    sa.Column('run_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.Text(), nullable=False),
    sa.Column('ended_at', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('correlated_events_count', sa.Integer(), nullable=False),
    sa.Column('ssh_sessions_count', sa.Integer(), nullable=False),
    sa.Column('source_correlated_file', sa.Text(), nullable=True),
    sa.Column('source_ssh_sessions_file', sa.Text(), nullable=True),
    sa.Column('scenario', sa.Text(), nullable=True),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('schema_migrations',
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('applied_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_table('attack_run_metadata',
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('attack_family', sa.Text(), nullable=False),
    sa.Column('attack_technique', sa.Text(), nullable=False),
    sa.Column('scenario', sa.Text(), nullable=False),
    sa.Column('tool', sa.Text(), nullable=True),
    sa.Column('tool_version', sa.Text(), nullable=True),
    sa.Column('target_host', sa.Text(), nullable=True),
    sa.Column('target_port', sa.Integer(), nullable=True),
    sa.Column('intensity', sa.Text(), nullable=True),
    sa.Column('parameters', sa.Text(), nullable=True),
    sa.Column('attack_start_ts', sa.Text(), nullable=True),
    sa.Column('attack_end_ts', sa.Text(), nullable=True),
    sa.Column('expected_behavior', sa.Text(), nullable=True),
    sa.Column('tool_version_check', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('operator', sa.Text(), nullable=True),
    sa.Column('manifest_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['observation_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id')
    )
    with op.batch_alter_table('attack_run_metadata', schema=None) as batch_op:
        batch_op.create_index('idx_attack_run_metadata_family', ['attack_family'], unique=False)
        batch_op.create_index('idx_attack_run_metadata_technique', ['attack_technique'], unique=False)

    op.create_table('correlated_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Text(), nullable=False),
    sa.Column('src_ip', sa.Text(), nullable=True),
    sa.Column('dst_ip', sa.Text(), nullable=True),
    sa.Column('src_port', sa.Integer(), nullable=True),
    sa.Column('dst_port', sa.Integer(), nullable=True),
    sa.Column('transport', sa.Text(), nullable=True),
    sa.Column('direction', sa.Text(), nullable=True),
    sa.Column('process_pid', sa.Integer(), nullable=True),
    sa.Column('process_name', sa.Text(), nullable=True),
    sa.Column('dns_matched', sa.Integer(), nullable=False),
    sa.Column('dns_method', sa.Text(), nullable=True),
    sa.Column('dns_time_delta_ms', sa.Integer(), nullable=True),
    sa.Column('dns_response_latency_ms', sa.Float(), nullable=True),
    sa.Column('tls_matched', sa.Integer(), nullable=False),
    sa.Column('tls_method', sa.Text(), nullable=True),
    sa.Column('tls_time_delta_ms', sa.Integer(), nullable=True),
    sa.Column('ssh_matched', sa.Integer(), nullable=False),
    sa.Column('ssh_method', sa.Text(), nullable=True),
    sa.Column('ssh_time_delta_ms', sa.Integer(), nullable=True),
    sa.Column('tcp_flow_matched', sa.Integer(), nullable=False),
    sa.Column('tcp_flow_method', sa.Text(), nullable=True),
    sa.Column('tcp_flow_time_delta_ms', sa.Integer(), nullable=True),
    sa.Column('http_matched', sa.Integer(), nullable=False),
    sa.Column('http_method', sa.Text(), nullable=True),
    sa.Column('http_time_delta_ms', sa.Integer(), nullable=True),
    sa.Column('process_context_matched', sa.Integer(), nullable=False),
    sa.Column('process_context_method', sa.Text(), nullable=True),
    sa.Column('file_activity_count', sa.Integer(), nullable=False),
    sa.Column('file_activity_method', sa.Text(), nullable=True),
    sa.Column('privilege_activity_count', sa.Integer(), nullable=False),
    sa.Column('privilege_activity_method', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['observation_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('correlated_events', schema=None) as batch_op:
        batch_op.create_index('idx_correlated_events_dst_ip', ['dst_ip'], unique=False)
        batch_op.create_index('idx_correlated_events_process_pid', ['process_pid'], unique=False)
        batch_op.create_index('idx_correlated_events_run_id', ['run_id'], unique=False)
        batch_op.create_index('idx_correlated_events_run_timestamp', ['run_id', 'timestamp'], unique=False)
        batch_op.create_index('idx_correlated_events_timestamp', ['timestamp'], unique=False)

    op.create_table('dns_events_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('dedup_key', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.Text(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=True),
    sa.Column('src_ip', sa.Text(), nullable=True),
    sa.Column('dst_ip', sa.Text(), nullable=True),
    sa.Column('src_port', sa.Integer(), nullable=True),
    sa.Column('dst_port', sa.Integer(), nullable=True),
    sa.Column('transport', sa.Text(), nullable=True),
    sa.Column('direction', sa.Text(), nullable=True),
    sa.Column('query_name', sa.Text(), nullable=True),
    sa.Column('query_type', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('rcode', sa.Integer(), nullable=True),
    sa.Column('answer_count', sa.Integer(), nullable=True),
    sa.Column('resolved_ip', sa.Text(), nullable=True),
    sa.Column('ttl', sa.Integer(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['observation_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'dedup_key', name='uq_dns_events_raw_run_dedup')
    )
    with op.batch_alter_table('dns_events_raw', schema=None) as batch_op:
        batch_op.create_index('idx_dns_events_raw_query_name', ['query_name'], unique=False)
        batch_op.create_index('idx_dns_events_raw_run_id', ['run_id'], unique=False)

    op.create_table('feature_windows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('window_start_ts', sa.Text(), nullable=False),
    sa.Column('window_end_ts', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('label', sa.Integer(), nullable=True),
    sa.Column('scenario', sa.Text(), nullable=True),
    sa.Column('attack_family', sa.Text(), nullable=True),
    sa.Column('attack_technique', sa.Text(), nullable=True),
    sa.Column('feature_version', sa.Text(), nullable=False),
    sa.Column('aggregation_version', sa.Text(), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('tcp_connect_count', sa.Integer(), nullable=False),
    sa.Column('tcp_close_count', sa.Integer(), nullable=False),
    sa.Column('dns_query_count', sa.Integer(), nullable=False),
    sa.Column('tls_connection_count', sa.Integer(), nullable=False),
    sa.Column('http_request_count', sa.Integer(), nullable=False),
    sa.Column('ssh_attempt_count', sa.Integer(), nullable=False),
    sa.Column('unique_dst_ip_count', sa.Integer(), nullable=False),
    sa.Column('unique_dst_port_count', sa.Integer(), nullable=False),
    sa.Column('unique_src_port_count', sa.Integer(), nullable=False),
    sa.Column('external_dst_ip_count', sa.Integer(), nullable=False),
    sa.Column('private_dst_ip_count', sa.Integer(), nullable=False),
    sa.Column('total_bytes_in', sa.Integer(), nullable=False),
    sa.Column('total_bytes_out', sa.Integer(), nullable=False),
    sa.Column('total_packets_in', sa.Integer(), nullable=False),
    sa.Column('total_packets_out', sa.Integer(), nullable=False),
    sa.Column('mean_flow_duration_sec', sa.Float(), nullable=True),
    sa.Column('max_flow_duration_sec', sa.Float(), nullable=True),
    sa.Column('failed_connection_count', sa.Integer(), nullable=False),
    sa.Column('failed_connection_ratio', sa.Float(), nullable=True),
    sa.Column('connections_per_sec', sa.Float(), nullable=True),
    sa.Column('bytes_per_sec_in', sa.Float(), nullable=True),
    sa.Column('bytes_per_sec_out', sa.Float(), nullable=True),
    sa.Column('packets_per_sec_in', sa.Float(), nullable=True),
    sa.Column('packets_per_sec_out', sa.Float(), nullable=True),
    sa.Column('interarrival_mean_ms', sa.Float(), nullable=True),
    sa.Column('interarrival_std_ms', sa.Float(), nullable=True),
    sa.Column('interarrival_p95_ms', sa.Float(), nullable=True),
    sa.Column('dst_port_entropy', sa.Float(), nullable=True),
    sa.Column('dst_ip_entropy', sa.Float(), nullable=True),
    sa.Column('well_known_port_ratio', sa.Float(), nullable=True),
    sa.Column('high_port_ratio', sa.Float(), nullable=True),
    sa.Column('external_destination_ratio', sa.Float(), nullable=True),
    sa.Column('unique_domain_count', sa.Integer(), nullable=False),
    sa.Column('nxdomain_count', sa.Integer(), nullable=False),
    sa.Column('nxdomain_ratio', sa.Float(), nullable=True),
    sa.Column('mean_domain_length', sa.Float(), nullable=True),
    sa.Column('max_domain_length', sa.Integer(), nullable=True),
    sa.Column('subdomain_depth_mean', sa.Float(), nullable=True),
    sa.Column('unique_resolved_ip_count', sa.Integer(), nullable=False),
    sa.Column('dns_response_latency_mean_ms', sa.Float(), nullable=True),
    sa.Column('dns_response_latency_p95_ms', sa.Float(), nullable=True),
    sa.Column('mean_label_length', sa.Float(), nullable=True),
    sa.Column('max_label_length', sa.Integer(), nullable=True),
    sa.Column('domain_label_entropy_mean', sa.Float(), nullable=True),
    sa.Column('base32_like_ratio', sa.Float(), nullable=True),
    sa.Column('base64_like_ratio', sa.Float(), nullable=True),
    sa.Column('hex_like_ratio', sa.Float(), nullable=True),
    sa.Column('unique_sni_count', sa.Integer(), nullable=False),
    sa.Column('missing_sni_count', sa.Integer(), nullable=False),
    sa.Column('missing_sni_ratio', sa.Float(), nullable=True),
    sa.Column('unique_ja4_count', sa.Integer(), nullable=False),
    sa.Column('ja4_entropy', sa.Float(), nullable=True),
    sa.Column('rare_ja4_ratio', sa.Float(), nullable=True),
    sa.Column('tls_version_distribution', sa.Text(), nullable=True),
    sa.Column('most_common_ja4', sa.Text(), nullable=True),
    sa.Column('most_common_ja4_count', sa.Integer(), nullable=True),
    sa.Column('http_unique_host_count', sa.Integer(), nullable=False),
    sa.Column('http_methods_distribution', sa.Text(), nullable=True),
    sa.Column('http_status_2xx_ratio', sa.Float(), nullable=True),
    sa.Column('http_status_4xx_ratio', sa.Float(), nullable=True),
    sa.Column('http_status_5xx_ratio', sa.Float(), nullable=True),
    sa.Column('mean_path_length', sa.Float(), nullable=True),
    sa.Column('mean_content_length', sa.Float(), nullable=True),
    sa.Column('process_exec_count', sa.Integer(), nullable=False),
    sa.Column('unique_binary_count', sa.Integer(), nullable=False),
    sa.Column('shell_spawn_count', sa.Integer(), nullable=False),
    sa.Column('interpreter_spawn_count', sa.Integer(), nullable=False),
    sa.Column('process_tree_depth_max', sa.Integer(), nullable=True),
    sa.Column('sensitive_file_event_count', sa.Integer(), nullable=False),
    sa.Column('privilege_event_count', sa.Integer(), nullable=False),
    sa.Column('sudo_exec_count', sa.Integer(), nullable=False),
    sa.Column('pkexec_count', sa.Integer(), nullable=False),
    sa.Column('su_exec_count', sa.Integer(), nullable=False),
    sa.Column('capability_event_count', sa.Integer(), nullable=False),
    sa.Column('seconds_since_last_privilege_event', sa.Float(), nullable=True),
    sa.Column('seconds_since_last_sensitive_file_access', sa.Float(), nullable=True),
    sa.Column('network_events_after_privilege_event', sa.Integer(), nullable=True),
    sa.Column('network_events_after_sensitive_file_access', sa.Integer(), nullable=True),
    sa.Column('ssh_success_count', sa.Integer(), nullable=False),
    sa.Column('ssh_failure_count', sa.Integer(), nullable=False),
    sa.Column('ssh_failure_ratio', sa.Float(), nullable=True),
    sa.Column('ssh_session_count', sa.Integer(), nullable=False),
    sa.Column('mean_ssh_session_duration_sec', sa.Float(), nullable=True),
    sa.Column('contributing_event_ids', sa.Text(), nullable=True),
    sa.Column('total_flow_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['observation_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feature_windows', schema=None) as batch_op:
        batch_op.create_index('idx_feature_windows_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('idx_feature_windows_label', ['label'], unique=False)
        batch_op.create_index('idx_feature_windows_run_id', ['run_id'], unique=False)
        batch_op.create_index('idx_feature_windows_timestamp', ['window_start_ts', 'window_end_ts'], unique=False)

    op.create_table('ssh_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('session_key', sa.Text(), nullable=True),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('src_ip', sa.Text(), nullable=True),
    sa.Column('src_port', sa.Integer(), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('earliest_event_ts', sa.Text(), nullable=True),
    sa.Column('auth_success_ts', sa.Text(), nullable=True),
    sa.Column('auth_method', sa.Text(), nullable=True),
    sa.Column('session_opened_ts', sa.Text(), nullable=True),
    sa.Column('session_closed_ts', sa.Text(), nullable=True),
    sa.Column('session_duration_seconds', sa.Float(), nullable=True),
    sa.Column('disconnected_ts', sa.Text(), nullable=True),
    sa.Column('tcp_connect_matched', sa.Integer(), nullable=False),
    sa.Column('tcp_connect_dst_ip', sa.Text(), nullable=True),
    sa.Column('tcp_connect_time_delta_ms', sa.Integer(), nullable=True),
    sa.Column('tcp_close_matched', sa.Integer(), nullable=False),
    sa.Column('tcp_close_timestamp', sa.Text(), nullable=True),
    sa.Column('connection_duration_seconds', sa.Float(), nullable=True),
    sa.Column('execve_matched', sa.Integer(), nullable=False),
    sa.Column('execve_binary', sa.Text(), nullable=True),
    sa.Column('execve_timestamp', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['observation_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ssh_sessions', schema=None) as batch_op:
        batch_op.create_index('idx_ssh_sessions_run_id', ['run_id'], unique=False)
        batch_op.create_index('idx_ssh_sessions_session_key', ['session_key'], unique=False)

    op.create_table('tcp_flows_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('dedup_key', sa.Text(), nullable=False),
    sa.Column('src_ip', sa.Text(), nullable=True),
    sa.Column('src_port', sa.Integer(), nullable=True),
    sa.Column('dst_ip', sa.Text(), nullable=True),
    sa.Column('dst_port', sa.Integer(), nullable=True),
    sa.Column('transport', sa.Text(), nullable=True),
    sa.Column('direction', sa.Text(), nullable=True),
    sa.Column('start_ts', sa.Text(), nullable=True),
    sa.Column('end_ts', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('handshake_completed', sa.Integer(), nullable=True),
    sa.Column('handshake_rtt_ms', sa.Float(), nullable=True),
    sa.Column('termination_reason', sa.Text(), nullable=True),
    sa.Column('packets_out', sa.Integer(), nullable=True),
    sa.Column('packets_in', sa.Integer(), nullable=True),
    sa.Column('bytes_out', sa.Integer(), nullable=True),
    sa.Column('bytes_in', sa.Integer(), nullable=True),
    sa.Column('retransmissions', sa.Integer(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['observation_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'dedup_key', name='uq_tcp_flows_raw_run_dedup')
    )
    with op.batch_alter_table('tcp_flows_raw', schema=None) as batch_op:
        batch_op.create_index('idx_tcp_flows_raw_run_id', ['run_id'], unique=False)

    op.create_table('dns_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correlated_event_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Text(), nullable=True),
    sa.Column('query_name', sa.Text(), nullable=True),
    sa.Column('query_type', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('rcode', sa.Integer(), nullable=True),
    sa.Column('answer_count', sa.Integer(), nullable=True),
    sa.Column('resolved_ip', sa.Text(), nullable=True),
    sa.Column('ttl', sa.Integer(), nullable=True),
    sa.Column('response_latency_ms', sa.Float(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['correlated_event_id'], ['correlated_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dns_observations', schema=None) as batch_op:
        batch_op.create_index('idx_dns_observations_correlated_event_id', ['correlated_event_id'], unique=False)
        batch_op.create_index('idx_dns_observations_query_name', ['query_name'], unique=False)
        batch_op.create_index('idx_dns_observations_resolved_ip', ['resolved_ip'], unique=False)

    op.create_table('file_activity_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correlated_event_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Text(), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('operations', sa.Text(), nullable=True),
    sa.Column('source_event_key', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['correlated_event_id'], ['correlated_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file_activity_events', schema=None) as batch_op:
        batch_op.create_index('idx_file_activity_correlated_event_id', ['correlated_event_id'], unique=False)
        batch_op.create_index('idx_file_activity_path', ['path'], unique=False)

    op.create_table('http_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correlated_event_id', sa.Integer(), nullable=False),
    sa.Column('request_timestamp', sa.Text(), nullable=True),
    sa.Column('response_timestamp', sa.Text(), nullable=True),
    sa.Column('method', sa.Text(), nullable=True),
    sa.Column('host', sa.Text(), nullable=True),
    sa.Column('path_hash', sa.Text(), nullable=True),
    sa.Column('path_length', sa.Integer(), nullable=True),
    sa.Column('user_agent_hash', sa.Text(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.Text(), nullable=True),
    sa.Column('content_length', sa.Integer(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['correlated_event_id'], ['correlated_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('http_observations', schema=None) as batch_op:
        batch_op.create_index('idx_http_observations_correlated_event_id', ['correlated_event_id'], unique=False)
        batch_op.create_index('idx_http_observations_host', ['host'], unique=False)
        batch_op.create_index('idx_http_observations_status_code', ['status_code'], unique=False)

    op.create_table('privilege_activity_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correlated_event_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Text(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('source_event_key', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['correlated_event_id'], ['correlated_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('privilege_activity_events', schema=None) as batch_op:
        batch_op.create_index('idx_privilege_activity_correlated_event_id', ['correlated_event_id'], unique=False)

    op.create_table('process_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correlated_event_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Text(), nullable=True),
    sa.Column('exec_id', sa.Text(), nullable=True),
    sa.Column('parent_exec_id', sa.Text(), nullable=True),
    sa.Column('parent_binary', sa.Text(), nullable=True),
    sa.Column('arguments', sa.Text(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('cwd', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['correlated_event_id'], ['correlated_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('process_observations', schema=None) as batch_op:
        batch_op.create_index('idx_process_observations_correlated_event_id', ['correlated_event_id'], unique=False)
        batch_op.create_index('idx_process_observations_exec_id', ['exec_id'], unique=False)

    op.create_table('tcp_flow_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correlated_event_id', sa.Integer(), nullable=False),
    sa.Column('start_ts', sa.Text(), nullable=True),
    sa.Column('end_ts', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('handshake_completed', sa.Integer(), nullable=True),
    sa.Column('handshake_rtt_ms', sa.Float(), nullable=True),
    sa.Column('termination_reason', sa.Text(), nullable=True),
    sa.Column('packets_out', sa.Integer(), nullable=True),
    sa.Column('packets_in', sa.Integer(), nullable=True),
    sa.Column('bytes_out', sa.Integer(), nullable=True),
    sa.Column('bytes_in', sa.Integer(), nullable=True),
    sa.Column('retransmissions', sa.Integer(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['correlated_event_id'], ['correlated_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tcp_flow_observations', schema=None) as batch_op:
        batch_op.create_index('idx_tcp_flow_observations_correlated_event_id', ['correlated_event_id'], unique=False)

    op.create_table('tls_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correlated_event_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Text(), nullable=True),
    sa.Column('sni', sa.Text(), nullable=True),
    sa.Column('ja4', sa.Text(), nullable=True),
    sa.Column('tls_version', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['correlated_event_id'], ['correlated_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tls_observations', schema=None) as batch_op:
        batch_op.create_index('idx_tls_observations_correlated_event_id', ['correlated_event_id'], unique=False)
        batch_op.create_index('idx_tls_observations_ja4', ['ja4'], unique=False)
        batch_op.create_index('idx_tls_observations_sni', ['sni'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tls_observations', schema=None) as batch_op:
        batch_op.drop_index('idx_tls_observations_sni')
        batch_op.drop_index('idx_tls_observations_ja4')
        batch_op.drop_index('idx_tls_observations_correlated_event_id')

    op.drop_table('tls_observations')
    with op.batch_alter_table('tcp_flow_observations', schema=None) as batch_op:
        batch_op.drop_index('idx_tcp_flow_observations_correlated_event_id')

    op.drop_table('tcp_flow_observations')
    with op.batch_alter_table('process_observations', schema=None) as batch_op:
        batch_op.drop_index('idx_process_observations_exec_id')
        batch_op.drop_index('idx_process_observations_correlated_event_id')

    op.drop_table('process_observations')
    with op.batch_alter_table('privilege_activity_events', schema=None) as batch_op:
        batch_op.drop_index('idx_privilege_activity_correlated_event_id')

    op.drop_table('privilege_activity_events')
    with op.batch_alter_table('http_observations', schema=None) as batch_op:
        batch_op.drop_index('idx_http_observations_status_code')
        batch_op.drop_index('idx_http_observations_host')
        batch_op.drop_index('idx_http_observations_correlated_event_id')

    op.drop_table('http_observations')
    with op.batch_alter_table('file_activity_events', schema=None) as batch_op:
        batch_op.drop_index('idx_file_activity_path')
        batch_op.drop_index('idx_file_activity_correlated_event_id')

    op.drop_table('file_activity_events')
    with op.batch_alter_table('dns_observations', schema=None) as batch_op:
        batch_op.drop_index('idx_dns_observations_resolved_ip')
        batch_op.drop_index('idx_dns_observations_query_name')
        batch_op.drop_index('idx_dns_observations_correlated_event_id')

    op.drop_table('dns_observations')
    with op.batch_alter_table('tcp_flows_raw', schema=None) as batch_op:
        batch_op.drop_index('idx_tcp_flows_raw_run_id')

    op.drop_table('tcp_flows_raw')
    with op.batch_alter_table('ssh_sessions', schema=None) as batch_op:
        batch_op.drop_index('idx_ssh_sessions_session_key')
        batch_op.drop_index('idx_ssh_sessions_run_id')

    op.drop_table('ssh_sessions')
    with op.batch_alter_table('feature_windows', schema=None) as batch_op:
        batch_op.drop_index('idx_feature_windows_timestamp')
        batch_op.drop_index('idx_feature_windows_run_id')
        batch_op.drop_index('idx_feature_windows_label')
        batch_op.drop_index('idx_feature_windows_entity')

    op.drop_table('feature_windows')
    with op.batch_alter_table('dns_events_raw', schema=None) as batch_op:
        batch_op.drop_index('idx_dns_events_raw_run_id')
        batch_op.drop_index('idx_dns_events_raw_query_name')

    op.drop_table('dns_events_raw')
    with op.batch_alter_table('correlated_events', schema=None) as batch_op:
        batch_op.drop_index('idx_correlated_events_timestamp')
        batch_op.drop_index('idx_correlated_events_run_timestamp')
        batch_op.drop_index('idx_correlated_events_run_id')
        batch_op.drop_index('idx_correlated_events_process_pid')
        batch_op.drop_index('idx_correlated_events_dst_ip')

    op.drop_table('correlated_events')
    with op.batch_alter_table('attack_run_metadata', schema=None) as batch_op:
        batch_op.drop_index('idx_attack_run_metadata_technique')
        batch_op.drop_index('idx_attack_run_metadata_family')

    op.drop_table('attack_run_metadata')
    op.drop_table('schema_migrations')
    op.drop_table('observation_runs')
    # ### end Alembic commands ###
