"""run quality and identity

Revision ID: 89742ced0b79
Revises: 5f9313b66658
Create Date: 2026-09-16 22:02:20.955669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89742ced0b79'
down_revision: Union[str, Sequence[str], None] = '5f9313b66658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attack_run_metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('run_uuid', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manifest_hash', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('allow_nonzero_exit', sa.Integer(), server_default='0', nullable=False))
        batch_op.create_index('idx_attack_run_metadata_run_uuid', ['run_uuid'], unique=True)

    with op.batch_alter_table('observation_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quality', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('failure_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observation_runs', schema=None) as batch_op:
        batch_op.drop_column('failure_reason')
        batch_op.drop_column('quality')

    with op.batch_alter_table('attack_run_metadata', schema=None) as batch_op:
        batch_op.drop_index('idx_attack_run_metadata_run_uuid')
        batch_op.drop_column('allow_nonzero_exit')
        batch_op.drop_column('manifest_hash')
        batch_op.drop_column('run_uuid')

    # ### end Alembic commands ###
