apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "dns-queries"
spec:
  kprobes:
  # ----- UDP DNS (the majority) -----
  - call: "udp_sendmsg"
    syscall: false
    args:
    - index: 0
      type: "sock"
    selectors:
    - matchArgs:
      - index: 0
        operator: "DPort"
        values:
        - "53"

  - call: "udp_recvmsg"
    syscall: false
    args:
    - index: 0
      type: "sock"
    selectors:
    - matchArgs:
      - index: 0
        operator: "SPort"
        values:
        - "53"

  # ----- TCP DNS (zone transfers, large answers, DNSSEC) -----
  - call: "tcp_connect"
    syscall: false
    args:
    - index: 0
      type: "sock"
    selectors:
    - matchArgs:
      - index: 0
        operator: "DPort"
        values:
        - "53"

  - call: "tcp_close"
    syscall: false
    args:
    - index: 0
      type: "sock"
    selectors:
    - matchArgs:
      - index: 0
        operator: "DPort"
        values:
        - "53"
