apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "ssh-sessions"
spec:
  kprobes:
  - call: "tcp_connect"
    syscall: false
    args:
    - index: 0
      type: "sock"
    selectors:
    - matchArgs:
      - index: 0
        operator: "DPort"
        values:
        - "22"

  - call: "tcp_close"
    syscall: false
    args:
    - index: 0
      type: "sock"
    selectors:
    - matchArgs:
      - index: 0
        operator: "DPort"
        values:
        - "22"

  - call: "sys_execve"
    syscall: true
    selectors:
    - matchBinaries:
      - operator: "In"
        values:
        - "/usr/sbin/sshd"
        - "/usr/bin/ssh"
        - "/usr/bin/ssh-agent"
